name: Black, Ruff and MyPy Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Or any version you prefer

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
  
    - name: Black linting
      run: |
        poetry run black --check .

    - name: Ruff Linting AstraPy
      run: |
        poetry run ruff astrapy

    - name: Ruff Linting Tests
      run: |
        poetry run ruff tests

    - name: Run MyPy AstraPy
      run: |
        poetry run mypy astrapy

    - name: Run MyPy Tests
      run: |
        poetry run mypy tests
