name: Black, Ruff and MyPy Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Or any version you prefer

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
  
    - name: Black linting
      run: |
        black --check .

    - name: Ruff Linting AstraPy
      run: |
        ruff astrapy

    - name: Ruff Linting Tests
      run: |
        ruff tests

    - name: Run MyPy AstraPy
      run: |
        mypy astrapy

    - name: Run MyPy Tests
      run: |
        mypy tests
